blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
     path('', views.index, name = 'index'),
     path('contact',views.contact, name = 'contact' ),
     path('home',views.HomeView.as_view(), name = 'home' ),
]

webpage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here

class Users(models.Model):
    id = models.IntegerField(primary_key = True)
    fullname = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 100)
    message = models.CharField(max_length = 300)
    pub_date = models.DateTimeField(' date published')

    def __str__(self):
        return self.fullname
    

blog/forms.py
from django import forms

class ContactForm(forms.Form):
    fullname = forms.CharField(max_length = 50, widget = forms.TextInput(attrs={"value":""}), required=True, label = "Full Name")
    email = forms.EmailField(max_length = 50, widget = forms.TextInput(attrs={"value":""}), required=True,  label = "Email")
    message = forms.CharField(max_length = 500, widget = forms.Textarea(attrs={"value":""}), required=True, label = "Message")

class LoginForm(forms.Form):
    username = forms.CharField(max_length = 50, widget = forms.TextInput(attrs={"value":""}), required=True, label = "Username")
    password = forms.CharField(max_length = 50, widget = forms.PasswordInput(attrs={"value":""}), required=True, label = "Password")

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.views.generic import ListView

from .models import Users
from .forms import ContactForm, LoginForm
# Create your views here.

def index(request):
    loginform = LoginForm(request.POST)
    if request.method == 'POST':
        if loginform.is_valid():
            data = loginform.cleaned_data
            username = data.get("username")
            password = data.get("password")
            access = authenticate(username = username, password = password)
            if access is not None:
                login(request, access)
                return HttpResponseRedirect(reverse('blog:home'))
            else:
                return HttpResponse("Incorrect Username or Password")

    return render(request, 'blog/index.html', {"form": loginform})



class HomeView(ListView):
    model = Users
    template_name = "blog/home.html"


def contact(request):
    #Inserta los datos del formulario en la db
    pub_date = timezone.now()
    contactform = ContactForm(request.POST)
    if request.method == 'POST':
        if contactform.is_valid():
            data = contactform.cleaned_data
            #print(data)
            db_register = Users(
                fullname = data.get("fullname"),
                email = data.get("email"),
                message = data.get("message"),
                pub_date = pub_date )
            db_register.save()
            return HttpResponseRedirect(reverse('blog:home'))
    else:
        return render(request, 'blog/contact.html', {'form':contactform})

blog/templates/blog/contact.html
<!DOCTYPE html>
<html lang=EN>
    <head>
        <meta charset="UTF-8">
        <title>Contact</title>
    </head>
    <body>
        <form method="POST" action = "{% url 'blog:contact' %}">
           
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    </body>
</html>

blog/templates/blog/home.html
<!DOCTYPE html>
<html lang=EN>
    <head>
        <meta charset="UTF-8">
        <title>Home</title>
    </head>
    <body>
        {%  if user.is_authenticated %}
            <h1> Welcome, {{ user.username }}</h1>
        {% else %}
            <h1> Welcome, new user. Please log in</h1>
        {% endif %}

        <h2>Users Comments</h2>
    {% for data in object_list %}
       <table>
           <tr>
               <td>Full name: </td>
               <td>{{data.fullname}}</td>
           </tr>

           <tr>
            <td>Email: </td>
            <td>{{data.email}}</td>
           </tr>

           <tr>
                <td>Message: </td>
                <td>{{data.message}}</td>
           </tr>

           <tr>
                <td>Date: </td>
                <td>{{data.pub_date}}</td>
           </tr>
           <br><br>

        
       </table>
    {% endfor%}
    </body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang=EN>
    <head>
        <meta charset="UTF-8">
        <title>Index</title>
    </head>
    <body>
        <h1>Login</h1>
        <form method="POST" action = "{% url 'blog:index' %}">
           
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    </body>
</html>